### ISSUE TITLE
Support for non-harmony services

### ISSUE THREAD

**Issue by frankinspace** [podaac/cmr-umm-updater#26]
Currently, the cmr-umm-updater will always replace the `URL` value with a harmony url
https://github.com/podaac/cmr-umm-updater/blob/develop/entrypoint.sh#L18-L21

There are cases where we want to use this action to publish non-harmony services (e.g. https://github.com/podaac/hydrocron/issues/77).

Need to add some logic to support modifying the URL with other values; not just harmony.

**Comment by frankinspace** [comment]
I think the easiest solution might be to only do the substitution if the URL is `https://harmony.earthdata.nasa.gov`.

More complicated solution would be to find a way to do environment-specific substitutions in general.

@sliu008 @jamesfwood thoughts?

**Comment by sliu008** [comment]
> I think the easiest solution might be to only do the substitution if the URL is `https://harmony.earthdata.nasa.gov`.
> 
> More complicated solution would be to find a way to do environment-specific substitutions in general.
> 
> @sliu008 @jamesfwood thoughts?

Yea we could do that, or add an option where we can pass in a url if there nothing passed in default it to use the environment and harmony
